image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint 
    - mongodb.mongodb-vscode    
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 3001
    onOpen: ignore  
    visibility: public
  - port: 27017
    onOpen: ignore  
    visibility: private